slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 2.0 # Reduced for more frequent updates
    resolution: 0.05
    min_laser_range: 0.12 # Set based on your lidar specs
    max_laser_range: 12.0 # Adjusted for typical indoor mapping
    minimum_time_interval: 0.2 # Reduced for better tracking
    transform_timeout: 0.5 # Increased timeout for Arduino communication
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters - tuned for calibrated robot
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05 # Smaller for smooth mapping with correct wheel size
    minimum_travel_heading: 0.15 # About 8.6 degrees - good for precise tracking
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters - optimized for calibrated robot
    distance_variance_penalty: 0.1 # Trust corrected encoder odometry more
    angle_variance_penalty: 0.3 # Trust angular odometry with correct base_width

    fine_search_angle_offset: 0.00175 # Tighter search for better precision
    coarse_search_angle_offset: 0.175 # Reduced coarse search
    coarse_angle_resolution: 0.0175 # Higher resolution
    minimum_angle_penalty: 0.7 # More forgiving for minor errors
    minimum_distance_penalty: 0.3 # More forgiving for distance errors
    use_response_expansion: true
    min_pass_through: 3 # Require more consistent matches
    occupancy_threshold: 0.12 # Slightly higher threshold
