controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  ros__parameters:
    publish_rate: 50  # Hz

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  ros__parameters:
    left_wheel_names: ['front_left_wheel_joint', 'back_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'back_right_wheel_joint']
    wheel_separation: 0.215446  # Updated to match your URDF calculation
    wheel_radius: 0.085         # Updated to your specification
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    publish_rate: 50            # Increased from 5 to 50 for smoother control
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    enable_odom_tf: true
    # Velocity and acceleration limits
    linear.x.max_velocity: 0.5    # m/s
    linear.x.min_velocity: -0.5   # m/s
    angular.z.max_velocity: 1.0   # rad/s
    angular.z.min_velocity: -1.0  # rad/s
