ros_arduino_bridge:
  ros__parameters:
    serial_port: "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
    baud_rate: 57600
    robot_params:
  ros__parameters:
    base_width: 0.208000 # Distance between left and right wheels (meters)
    wheel_radius: 0.042500 # Wheel radius (meters)
    encoder_ticks_per_rev: 870 # Encoder ticks per wheel revolution
    odom_frame: "odom"
    base_frame: "base_link"
    imu_frame: "imu_link"
    ultrasonic_left_frame: "ultrasonic_left_link"
    ultrasonic_right_frame: "ultrasonic_right_link"
