#!/bin/bash

# Script to clean up redundant files after switching to separated approach

echo "✅ Cleanup already completed!"
echo ""
echo "Old redundant scripts have been moved to old_scripts/ directory:"
echo "  - 01_hardware_interface.sh → old_scripts/ (replaced by 01_arduino_only.sh + 02_lidar_only.sh)"
echo "  - 04_lidar_troubleshoot.sh → old_scripts/ (functionality merged into 02_lidar_only.sh)"
echo ""
echo "📁 Current active Pi scripts:"
echo ""
echo "Hardware Control:"
echo "  ✅ 01_arduino_only.sh      - Arduino bridge + robot state publisher"
echo "  ✅ 02_lidar_only.sh        - LiDAR with multiple test configurations"
echo ""
echo "Setup & Diagnostics:"
echo "  ✅ 02_setup_test.sh        - Hardware connection testing"
echo "  ✅ 03_network_config.sh    - Network configuration"
echo "  ✅ fix_usb_permissions.sh  - USB permission fixes"
echo ""
echo "Maintenance:"
echo "  ✅ cleanup_old_scripts.sh  - This script"
echo ""
echo "🎯 Recommended Pi workflow:"
echo "  Terminal 1: ./01_arduino_only.sh"
echo "  Terminal 2: ./02_lidar_only.sh"
echo ""
echo "💡 For troubleshooting, run 02_lidar_only.sh and choose option 4 (minimal config)"

echo ""
echo "See COMPLETE_WORKFLOW.md for the new workflow steps."