slam_toolbox:
  ros__parameters:
    # LAPTOP SLAM LOCALIZATION CONFIGURATION
    # This config is for localization mode - using previously saved serialized maps
    # Use this when you want to navigate with an existing map (not create new maps)

    # Solver configuration - full power
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # CRITICAL: Set to localization mode (not mapping)
    mode: localization

    # Map file configuration - IMPORTANT!
    # This should be the absolute path to your serialized map WITHOUT extension
    # Example: /home/username/ros2_ws/maps/my_map (no .data or .posegraph)
    # This will be overridden by launch file parameter
    map_file_name: /home/allen-wachio/ros2_ws/maps/default_map

    # Start at the first node of the pose graph (where mapping started)
    map_start_at_dock: true

    # Map loading settings
    map_start_pose: [0.0, 0.0, 0.0] # x, y, yaw (will use dock if map_start_at_dock is true)

    # Processing parameters - laptop can handle high frequency
    debug_logging: false
    throttle_scans: 1 # Process all scans for accurate localization
    transform_publish_period: 0.02 # 50Hz
    map_update_interval: 5.0 # Less frequent in localization mode
    resolution: 0.05
    min_laser_range: 0.12
    max_laser_range: 12.0
    minimum_time_interval: 0.2 # Slightly slower for stability
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Localization parameters - tuned for accurate position tracking
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # Loop closure - can be disabled or reduced in localization mode
    loop_search_maximum_distance: 3.0
    do_loop_closing: true # Keep enabled for better localization
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop closure parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher parameters - trust calibrated odometry
    distance_variance_penalty: 0.1
    angle_variance_penalty: 0.3

    fine_search_angle_offset: 0.00175
    coarse_search_angle_offset: 0.175
    coarse_angle_resolution: 0.0175
    minimum_angle_penalty: 0.7
    minimum_distance_penalty: 0.3
    use_response_expansion: true
    min_pass_through: 3
    occupancy_threshold: 0.12
